<?php

return [

    // General CP
    'dashboard' => 'Панель управления',
    'nav_dashboard' => 'Главная',
    'sneak_peek' => 'Быстрый просмотр',
    'sneak_peeking' => 'Идёт быстрый просмотр',
    'view_site' => 'Посмотреть сайт',
    'search_for_anything' => 'Поиск чего нибудь...',

    // Pages
    'pages' => 'Страница|Страницы',
    'nav_pages' => 'Страницы',
    'create_page_button' => 'Создать страницу',
    'edit_homepage_button' => 'Изменить главную страницу',
    'create_page' => 'Создать новую страницу',
    'page_created' => 'Страница создана',
    'editing_page' => 'Изменение страницы',
    'page_updated' => 'Страница обновлена',
    'home' => 'Home',
    'pages_empty_heading' => 'Страницы сайта',
    'pages_empty' => 'Pages are used to create the various sections and URL structures of your site, as well as manage their respective content.',
    'show_urls' => 'Показать ссылки',
    'show_titles' => 'Показать заголовки',
    'choose_page_type' => 'Выберите тип страницы',
    'parent_page' => 'Основная страница',

    // Collections
    'collections' => 'Коллекция|Коллекции',
    'nav_collections' => 'Коллекции',
    'manage_collections' => 'Manage Collections',
    'create_collection_button' => 'Create Collection',
    'create_collection' => 'Create a New Collection',
    'collection_created' => ':title Created',
    'editing_collection' => 'Editing :collection',
    'collection_updated' => ':title Updated',
    'collections_empty' => 'Collections are containers that hold groups of similar entries all following the same URL pattern.',

    // Entries
    'entries' => 'Entry|Entries',
    'nav_entries' => 'Entries',
    'create_entry_button' => 'Create Entry',
    'create_entry' => 'Create a New :collection Entry',
    'entry_created' => 'Entry Created',
    'editing_entry' => 'Editing Entry',
    'entry_updated' => 'Entry Updated',
    'entries_empty_heading' => ':type Entries',
    'entries_empty' => 'Entries are bits of content that have their own URL and are often shown in lists, like blog posts, press releases, and events.',

    // Taxonomies
    'taxonomies' => 'Taxonomy|Taxonomies',
    'nav_taxonomies' => 'Taxonomies',
    'create_taxonomy' => 'Create New Taxonomy',
    'create_taxonomy_button' => 'Create Taxonomy',
    'manage_taxonomies' => 'Manage Taxonomies',
    'editing_taxonomy' => 'Editing taxonomy',
    'taxonomy_updated' => 'Taxonomy Updated',
    'taxonomy_created' => 'Taxonomy Created',
    'taxonomies_empty_heading' => 'Taxonomies',
    'taxonomies_empty' => 'A Taxonomy is a system of classifying data around a set of unique characteristics, such as category or color.',

    'taxonomy_terms' => 'Term|Terms',
    'create_taxonomy_term_button' => 'Create :term',
    'create_taxonomy_term' => 'Create a New :term',
    'taxonomy_term_created' => 'Taxonomy term created',
    'taxonomy_terms_empty_heading' => 'Terms in :term',
    'taxonomy_terms_empty' => 'Where a Taxonomy is the grouping, a Term is the actual label applied to a piece of content. For example, "Red" would be a term in "Colors".',

    // Globals
    'globals' => 'Global|Globals',
    'nav_globals' => 'Globals',
    'manage_global_sets' => 'Manage Global Sets',
    'create_global_set_button' => 'Create Global Set',
    'create_global_set' => 'Create New Global Set',
    'global_set_created' => ':type created',
    'editing_globals' => 'Editing Globals',
    'globals_updated' => 'Globals Updated',
    'globals_empty_heading' => 'Global Sets',
    'globals_empty' => 'Global sets are groups of variables that represent content that isn\'t tied to a URL, such as company name, address, contact info, or even template level settings like limits, offsets, and show/hide toggles.',
    'general_globals' => 'General',
    'globals_title_instructions' => "Use a proper noun. For example: Footer Content, or Company Info.",
    'globals_slug_instructions' => "This is the variable used in your templates. For example: <code>footer_content</code> or <code>company_info</code>.",
    'globals_fieldset_instructions' => "Pick which group of fields you want to use to manage this fieldset.",

    // Assets
    'assets' => 'Asset|Assets',
    'nav_assets' => 'Assets',
    'new_asset' => 'New asset',
    'browse_assets' => 'Browse Assets',
    'browsing_assets' => 'Browsing Assets',
    'creating_asset' => 'Creating asset',
    'asset_created' => 'Asset created',
    'editing_asset' => 'Editing asset',
    'asset_updated' => 'Asset updated',
    'drop_to_upload' => 'Drop to Upload',
    'upload_asset' => 'Upload asset',
    'new_folder' => 'New Folder',
    'uploads' => 'Upload|Uploads',
    'filename' => 'Filename',
    'filesize' => 'File size',
    'date_modified' => 'Date modified',
    'parent_folder' => 'Parent folder',
    'asset_folder_empty_heading' => 'This folder contains no assets.',
    'asset_folder_empty' => 'You may upload new assets into this folder by dragging and dropping files into the outlined area above.',
    'focal_point' => 'Focal point',
    'focal_point_label' => 'Click image to adjust the focal point',
    'focal_point_instructions' => 'The focal point is used when cropping so the most important part of the image is not removed.',

    // Asset Containers
    'asset_containers' => 'Asset Container|Asset Containers',
    'manage_asset_containers' => 'Manage Asset Containers',
    'new_asset_container' => 'New Asset Container',
    'creating_asset_container' => 'Creating Asset Container',
    'asset_container_created' => 'Asset Container created',
    'editing_asset_container' => 'Editing Asset Container',
    'asset_container_updated' => 'Asset Container updated',
    'asset_containers_empty_heading' => 'There are no configured asset containers.',
    'asset_containers_empty' => 'Each asset container can be a location on your file system, which can either be publicly accessible or protected from prying eyes.',

    // Users
    'users' => 'Пользователь|Пользователи',
    'nav_users' => 'Пользователи',
    'create_user_button' => 'Create User',
    'create_user' => 'Create a User',
    'user_created' => 'User created',
    'editing_user' => 'Editing User',
    'user_updated' => 'User updated',
    'send_activation_email' => 'Send activation email',
    'my_account' => 'Мой аккаунт',
    'logout' => 'Выход',

    // Roles
    'roles' => 'Role|Roles',
    'nav_user-roles' => 'User Roles',
    'create_role_button' => 'Create Role',
    'creating_role' => 'Create a Role',
    'role_created' => 'Role created',
    'editing_role' => 'Editing Role',
    'role_updated' => 'Role Updated',
    'roles_empty_heading' => 'User Roles',
    'roles_empty' => 'User Roles allow you to group a number of permissions under a single label. For example, editor, publisher, and admin.',

    // Permissions
    'permissions' => 'Permission|Permissions',
    'access' => 'Доступ',

    // User Groups
    'usergroups' => 'User Group|User Groups',
    'nav_user-groups' => 'User Groups',
    'create_usergroup_button' => 'Create Group',
    'creating_usergroup' => 'Creating User Group',
    'usergroup_created' => 'User Group created',
    'editing_usergroup' => 'Editing User Group',
    'usergroup_updated' => 'User Group updated',
    'usergroups_empty_heading' => 'User Groups',
    'usergroups_empty' => 'User Groups allow you mix and match different roles and users together into a single group.',

    // Settings
    'settings' => 'Setting|Settings',
    'nav_settings' => 'Settings',
    'settings_cp' => 'Control Panel',
    'settings_routes' => 'Routes',
    'settings_search' => 'Search',
    'settings_system' => 'System',
    'settings_assets' => 'Assets',
    'settings_caching' => 'Caching',
    'settings_debug' => 'Debugging',
    'settings_email' => 'Email',
    'settings_theming' => 'Theming',
    'settings_users' => 'Users',

    // Addons
    'addons' => 'Addon|Addons',
    'nav_addons' => 'Addons',
    'addons_empty_heading' => 'There are no addons',
    'addons_empty' => 'Addons extend the functionality of Statamic.',

    // Fieldsets
    'fieldset' => 'Fieldset',
    'fieldsets' => 'Fieldset|Fieldsets',
    'nav_fieldsets' => 'Fieldsets',
    'create_fieldset_button' => 'Create Fieldset',
    'create_fieldset' => 'Create a Fieldset',
    'fieldset_created' => 'Fieldset created',
    'editing_fieldset' => 'Editing Fieldset',
    'fieldset_updated' => 'Fieldset updated',
    'fieldsets_empty' => 'Fieldsets let you create and manage reusable groups of fieldtypes that in turn mange your content. This is where content modeling happens.',

    // Forms
    'form' => 'Form',
    'forms' => 'Form|Forms',
    'nav_forms' => 'Forms',
    'forms_empty' => 'Forms collect, display, and report user submitted reponses.',
    'create_form' => 'Create Form',
    'form_updated' => 'Form updated',
    'form_created' => 'Form created',
    'response' => 'response|responses',
    'empty_responses' => 'This form is awaiting responses.',
    'create_formset' => 'Create Formset',
    'editing_formset' => 'Editing Formset',
    'export' => 'Export',
    'export_csv' => 'Export as CSV',
    'export_json' => 'Export as JSON',

    // Updater
    'nav_updater' => 'Updater',
    'upgrade_to_latest' => 'Upgrade to Latest',
    'upgrade_to_version' => 'Upgrade to :version',
    'downgrade_to_version' => 'Downgrade to :version',
    'update_available' => 'Update Available',
    'up_to_date' => 'Up to date!',
    'current_version' => 'Current Version',
    'released_on_date' => 'Released on :date',

    // Importers
    'nav_import' => 'Импорт',

    // Things
    'thing_created' => ':thing created.',
    'thing_updated' => ':thing updated.',
    'thing_deleted' => ':thing deleted.',
    'thing_configure' => 'Configure :thing',
    'thing_saved' => ':thing saved.',
    'thing_editing' => 'Editing :thing',

    // Statuses
    'statuses' => 'Status|Statuses',
    'status_pending' => 'Pending',
    'status_active' => 'Active',
    'published' => 'Published',

    // Verbs and helpers
    'actions' => 'Action|Actions',
    'add' => 'Добавить',
    'edit' => 'Изменить',
    'view' => 'Просмотр',
    'update' => 'Обновить',
    'delete' => 'Удалить',
    'duplicate' => 'Duplicate',
    'manage' => 'Упаравлять',
    'create' => 'Создать',
    'reorder' => 'Отсортировать',
    'submit' => 'Отправить',
    'save' => 'Сохранить',
    'saving' => 'Сохранение',
    'save_changes' => 'Сохранить изменения',
    'save_and_continue' => 'Сохранить и продолжить',
    'are_you_sure' => 'Are you sure?',
    'yes_im_sure' => 'Yes, I\'m sure',
    'refresh' => 'Обновить',
    'cancel' => 'Отмена',
    'loading' => 'Загрузка',
    'expand' => 'Развернуть',
    'collapse' => 'Свернуть',
    'edit_layout' => 'Edit Layout',
    'save_layout' => 'Save Layout',
    'toggle_dropdown' => 'Toggle Dropdown',
    'confirm_delete_items' => 'This item will be deleted|The selected items will be deleted',
    'configure' => 'Configure',
    'browse' => 'Browse',
    'select' => 'Select',
    'add_row' => 'Add Row',

    // Misc
    'fields' => 'Поле|Поля',
    'locales' => 'Locale|Locales',
    'keys' => 'Key|Keys',
    'values' => 'Value|Values',
    'names' => 'Name|Names',
    'usernames' => 'Username|Usernames',
    'emails' => 'Email|Emails',
    'passwords' => 'Password|Passwords',
    'confirm_password' => 'Confirm Password',
    'remember_me' => 'Remember me',
    'title' => 'Заголовок',
    'titles' => 'Заголовок|Заголовки',
    'slug' => 'ЧПУ',
    'slugs' => 'ЧПУ|ЧПУ',
    'rows' => 'Строка|Строки',
    'columns' => 'Колонка|Колонки',
    'folders' => 'Folder|Folders',
    'date' => 'Дата',
    'dates' => 'Date|Dates',
    'date_and_time' => 'Date and Time',
    'datestring' => 'Date',
    'add_date' => 'Add date',
    'add_time' => 'Add time',
    'login' => 'Login',
    'new' => 'Новая',
    'or' => 'или',
    'order' => 'Order',
    'version' => 'Version',
    'versions' => 'Version|Versions',
    'developer' => 'Developer',
    'developers' => 'Developer|Developers',
    'description' => 'Description',
    'descriptions' => 'Description|Descriptions',
    'name' => 'Имя',
    'username' => 'Username',
    'email' =>'Email',
    'done' => 'Готово',
    'close' => 'Закрыть',
    'templates' => 'Template|Templates',
    'authors' => 'Author|Authors',
    'installer' => 'Installer',
    'search' => 'Поиск',

];
